package backend;

import java.sql.Connection;
import java.sql.Statement;

public class Main {

    public static void main(String[] args) {

        try {
            Connection con = DBC.getConnection();
            Statement st = con.createStatement();

            st.executeUpdate("DROP TABLE IF EXISTS users");

            st.executeUpdate(
                "CREATE TABLE users (" +
                "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "role VARCHAR(20) NOT NULL," +
                "name VARCHAR(100) NOT NULL," +
                "email VARCHAR(100) NOT NULL," +
                "phone VARCHAR(20)," +
                "shop_name VARCHAR(100)," +
                "admin_id VARCHAR(50)," +
                "password VARCHAR(100) NOT NULL" +
                ")"
            );

            System.out.println("Users table updated successfully!");

            st.executeUpdate(
                "CREATE TABLE IF NOT EXISTS products (" +
                "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "name VARCHAR(100) NOT NULL," +
                "price DECIMAL(10,2) NOT NULL," +
                "description VARCHAR(255)," +
                "image VARCHAR(255)" +
                ")"
            );

            System.out.println("Products table ready!");

            st.executeUpdate(
                "CREATE TABLE IF NOT EXISTS orders (" +
                "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "user_email VARCHAR(100) NOT NULL," +
                "product_name VARCHAR(100) NOT NULL," +
                "quantity INTEGER NOT NULL," +
                "total_price DECIMAL(10,2) NOT NULL," +
                "status VARCHAR(30) DEFAULT 'Placed'," +
                "order_date VARCHAR(30)" +
                ")"
            );

            System.out.println("Orders table ready!");

            st.close();
            con.close();

            System.out.println("Database setup completed successfully!");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}